name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - uses: Azure/github-actions/login@master
      env: 
        AZURE_SERVICE_APP_ID: ${{ secrets.AZURE_SERVICE_APP_ID }}
        AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
        AZURE_SERVICE_TENANT: ${{ secrets.AZURE_SERVICE_TENANT }}
        AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}

  terraform-init:
    - uses: hashicorp/terraform-github-actions/init@v0.4.4
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "."
    
  terraform-validate:
    needs: terraform-init
    - uses: hashicorp/terraform-github-actions/validate@v0.4.4
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "."