name: build

on: [push]

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
  ARM_TENANT_ID: ${{ secrets.AZURE_SERVICE_TENANT }}
  TF_VAR_gateway_connection_shared_key: ${{ secrets.TF_VAR_gateway_connection_shared_key }}
  TF_VAR_local_gateway_public_ip: ${{ secrets.TF_VAR_local_gateway_public_ip }}

jobs:
  terraform-integration:
    name: Terraform tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1
    - name: Run terraform init
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "."
      uses: hashicorp/terraform-github-actions/init@v0.4.4
    - name: Run terraform validate
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "."
      uses: hashicorp/terraform-github-actions/validate@v0.4.4
    - name: Run terraform plan
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "."
        TF_ACTION_WORKSPACE: "default"
      uses: hashicorp/terraform-github-actions/plan@v0.4.4
    - name: Run terraform apply (building environment)
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "."
        TF_ACTION_WORKSPACE: "default"
      uses: hashicorp/terraform-github-actions/apply@v0.4.4
    - name: Run terraform plan -destroy
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "."
        TF_ACTION_WORKSPACE: "default"
      uses: lufussel/terraform-github-actions/plandestroy@v0.4.6
    - name: Run terraform destroy (cleaning up environment)
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "."
        TF_ACTION_WORKSPACE: "default"
      uses: lufussel/terraform-github-actions/destroy@v0.4.6

