name: build

on: [push]

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
  ARM_TENANT_ID: ${{ secrets.AZURE_SERVICE_TENANT }}

jobs:
  terraform-integration:
    name: Terraform integration tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - uses: hashicorp/terraform-github-actions/init@v0.4.4
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "."

    - uses: hashicorp/terraform-github-actions/validate@v0.4.4
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "."

    - uses: hashicorp/terraform-github-actions/plan@v0.4.4
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "."
        TF_ACTION_WORKSPACE: "default"
        

    - uses: hashicorp/terraform-github-actions/apply@v0.4.4
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "."
        TF_ACTION_WORKSPACE: "default"

    - uses: lufussel/terraform-github-actions/plandestroy@v0.4.9
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "."
        TF_ACTION_WORKSPACE: "default"

    - uses: lufussel/terraform-github-actions/destroy@v0.4.9
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "."
        TF_ACTION_WORKSPACE: "default"

